site_name: PHP Chess
site_url: https://chesslablab.github.io/php-chess/
theme:
  name: mkdocs
nav:
  - Getting Started:
    - Your First Move: your-first-move.md
    - Read Moves: read-moves.md
  - Data Conversion: data-conversion.md
  - Heuristics: heuristics.md
  - Chess Tutor: chess-tutor.md
  - Play Chess: play-chess.md
