site_name: PHP Chess
site_url: https://chesslablab.github.io/php-chess/
theme:
  name: mkdocs
nav:
  - Getting Started: getting-started.md
  - Data Conversion: data-conversion.md
  - Heuristics: heuristics.md
  - Chess Tutor: chess-tutor.md
  - Play Chess: play-chess.md
